[package]
name = "ordinals_dns"
version = "0.0.0"
edition = "2021"

[dependencies]
async-trait = "0.1.81"
hickory-server = "0.24.1"
tokio = { version = "1.39.3", features = ["macros", "rt-multi-thread", "net"] }
