services:
  bitcoin-core:
    build:
      context: ./regtest_node
      dockerfile: Dockerfile
    ports:
      - 18443:18443 # RPC
      - 18444:18444 # P2P
    volumes:
      - bitcoin-core:/root/.bitcoin

  # Use https://nostrdebug.com/ connected to ws://loclalhost:8080 to test
  nostr-relay:
    image: scsibug/nostr-rs-relay:0.8.8
    ports:
      - 8080:8080
    volumes:
      - nostr-relay:/usr/src/app/db


volumes:
  bitcoin-core:
    driver: local

  nostr-relay:
    driver: local
