[package]
name = "dns-wallet"
version = "0.1.0"
edition = "2024"

[dependencies]
bdk = { version = "0.22", default-features = false, features = ["all-keys", "key-value-db", "rpc"]}
dirs-next = "2.0"
dotenvy = "0.15.7"
hex = "0.4.3"
